// GENERATED by scripts/gen-ops.mjs from schema/ops.json - do not edit.

export const ENUMS = {"message_kinds":["info","question","advice","proposal","decision","review","warning","done"],"roles":["advisor","reviewer","coeditor","delegate"],"project_roles":["viewer","contributor","decider","admin"],"stances":["support","support-with-reservation","object","abstain","need-more-info"],"doc_kinds":["note","diagnosis","plan","proposal","decision","review","adr"],"note_contexts":["reflection","discussion","meeting","other"],"memory_kinds":["strategy","overview","convention","architecture","decision","pitfall","glossary"],"consensus_rules":["unanimous","majority","no-objection"],"routine_statuses":["active","paused","retired"],"routine_outcomes":["ok","issues","failed"]} as const;

export const CLIENT_VERSION = "0.12.0";   // package.json: compared with the server's in whoami

export interface OpArgs {
  ask: { session: string; claim: string; to: string; body: string; role?: string; kind?: string; client_id?: string | null; };
  check: { session: string; files: string[]; };
  claim: { session: string; scope: string; tree?: boolean | null; note?: string; ttl?: number; release_on_commit?: boolean; client_id?: string | null; };
  context: { session: string; };
  decide: { session: string; discussion: string; decision: string; proposal?: string | null; consensus?: boolean; reason?: string; };
  discuss: { session: string; topic: string; claim?: string | null; participants?: string[] | null; rule?: string; quorum?: number | null; deadline?: string | null; client_id?: string | null; };
  discussion: { discussion: string; session?: string | null; };
  discussions: { project?: string | null; status?: string; session?: string | null; };
  doc_create: { session: string; title: string; kind?: string; content?: string; client_id?: string | null; };
  doc_edit: { session: string; document: string; base_revision: number; content: string; message?: string; client_id?: string | null; };
  doc_history: { document: string; session?: string | null; };
  doc_import: { session: string; title: string; content: string; author?: string; context?: string; ai_assisted?: boolean | null; source?: string; client_id?: string | null; };
  doc_patch: { session: string; document: string; base_revision: number; patch: string; message?: string; client_id?: string | null; };
  doc_show: { document: string; revision?: number | null; session?: string | null; };
  docs: { project?: string | null; kind?: string | null; session?: string | null; };
  end: { session: string; };
  events: { after?: number; project?: string | null; limit?: number; session?: string | null; };
  fence_check: { claim: string; fence: number; session?: string | null; };
  grant: { session: string; claim: string; to: string; role: string; scope?: string | null; };
  heartbeat: { session: string; status?: string; };
  inbox: { session?: string | null; after?: number | null; to_me?: boolean; sender?: string | null; kind?: string | null; project?: string | null; limit?: number | null; unresolved?: boolean; };
  locks: { project?: string | null; all?: boolean; owner_session?: string | null; session?: string | null; };
  member_remove: { session: string; name: string; project?: string | null; client_id?: string | null; };
  member_set: { session: string; name: string; role: string; project?: string | null; client_id?: string | null; };
  members: { session?: string | null; project?: string | null; };
  memory: { project?: string | null; kind?: string | null; query?: string | null; include_archived?: boolean; session?: string | null; };
  memory_add: { session: string; kind: string; title: string; content: string; source?: string; client_id?: string | null; };
  memory_edit: { session: string; memory: string; base_revision: number; content: string; status?: string | null; };
  poll: { session: string; };
  post: { session: string; body: string; kind?: string; to?: string | null; reply_to?: number | null; claim?: string | null; client_id?: string | null; };
  post_commit: { session: string; sha: string; files: string[]; };
  presence: { project?: string | null; include_dead?: boolean; session?: string | null; };
  profile_set: { session: string; provider?: string | null; model_id?: string | null; model_family?: string | null; category?: string | null; reasoning_level?: string | null; capabilities?: string[] | null; };
  projects: { session?: string | null; };
  propose: { session: string; discussion: string; body: string; supersedes?: string | null; client_id?: string | null; };
  react: { session: string; proposal: string; stance: string; comment?: string; };
  release: { session: string; claim?: string | null; all?: boolean; };
  renew: { session: string; claim: string; ttl?: number; };
  reply: { session: string; message: number; body: string; kind?: string; client_id?: string | null; };
  resolve: { session: string; message: number; resolution?: string; client_id?: string | null; };
  revoke: { session: string; claim: string; to: string; role: string; };
  role_accept: { session: string; claim: string; role: string; };
  role_decline: { session: string; claim: string; role: string; reason?: string; };
  roles: { claim: string; session?: string | null; };
  routine_create: { session: string; title: string; instructions?: string; every?: string | null; on_commit?: boolean; paths?: string[] | null; client_id?: string | null; };
  routine_done: { session: string; routine: string; result?: string; outcome?: string; };
  routine_get: { routine: string; session?: string | null; };
  routine_start: { session: string; routine: string; };
  routine_update: { session: string; routine: string; status?: string | null; every?: string | null; instructions?: string | null; on_commit?: boolean | null; paths?: string[] | null; title?: string | null; };
  routines: { project?: string | null; due?: boolean; include_retired?: boolean; session?: string | null; };
  server_info: {  };
  status: { project?: string | null; session?: string | null; };
  suggest: { project?: string | null; category?: string | null; capability?: string[] | null; reasoning_level?: string | null; exclude_session?: string | null; session?: string | null; };
  task_accept: { session: string; task: string; };
  task_cancel: { session: string; task: string; note?: string; };
  task_create: { session: string; title: string; description?: string; priority?: number; claim?: string | null; assign?: string | null; category?: string | null; after?: string[] | null; client_id?: string | null; };
  task_decline: { session: string; task: string; reason?: string; };
  task_done: { session: string; task: string; note?: string; };
  task_get: { task: string; session?: string | null; };
  task_link: { session: string; task: string; after: string[]; remove?: boolean; };
  tasks: { project?: string | null; status?: string | null; assigned_session?: string | null; session?: string | null; };
  thread: { message: number; session?: string | null; };
  whoami: { family: string; project?: string; user?: string | null; model?: string | null; client_id?: string | null; };
}

export type OpName = keyof OpArgs;

export const OPS: Record<OpName, { kind: "read" | "write"; params: readonly string[] }> = {
 "ask": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "to",
   "body",
   "role",
   "kind",
   "client_id"
  ]
 },
 "check": {
  "kind": "read",
  "params": [
   "session",
   "files"
  ]
 },
 "claim": {
  "kind": "write",
  "params": [
   "session",
   "scope",
   "tree",
   "note",
   "ttl",
   "release_on_commit",
   "client_id"
  ]
 },
 "context": {
  "kind": "read",
  "params": [
   "session"
  ]
 },
 "decide": {
  "kind": "write",
  "params": [
   "session",
   "discussion",
   "decision",
   "proposal",
   "consensus",
   "reason"
  ]
 },
 "discuss": {
  "kind": "write",
  "params": [
   "session",
   "topic",
   "claim",
   "participants",
   "rule",
   "quorum",
   "deadline",
   "client_id"
  ]
 },
 "discussion": {
  "kind": "read",
  "params": [
   "discussion",
   "session"
  ]
 },
 "discussions": {
  "kind": "read",
  "params": [
   "project",
   "status",
   "session"
  ]
 },
 "doc_create": {
  "kind": "write",
  "params": [
   "session",
   "title",
   "kind",
   "content",
   "client_id"
  ]
 },
 "doc_edit": {
  "kind": "write",
  "params": [
   "session",
   "document",
   "base_revision",
   "content",
   "message",
   "client_id"
  ]
 },
 "doc_history": {
  "kind": "read",
  "params": [
   "document",
   "session"
  ]
 },
 "doc_import": {
  "kind": "write",
  "params": [
   "session",
   "title",
   "content",
   "author",
   "context",
   "ai_assisted",
   "source",
   "client_id"
  ]
 },
 "doc_patch": {
  "kind": "write",
  "params": [
   "session",
   "document",
   "base_revision",
   "patch",
   "message",
   "client_id"
  ]
 },
 "doc_show": {
  "kind": "read",
  "params": [
   "document",
   "revision",
   "session"
  ]
 },
 "docs": {
  "kind": "read",
  "params": [
   "project",
   "kind",
   "session"
  ]
 },
 "end": {
  "kind": "write",
  "params": [
   "session"
  ]
 },
 "events": {
  "kind": "read",
  "params": [
   "after",
   "project",
   "limit",
   "session"
  ]
 },
 "fence_check": {
  "kind": "read",
  "params": [
   "claim",
   "fence",
   "session"
  ]
 },
 "grant": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "to",
   "role",
   "scope"
  ]
 },
 "heartbeat": {
  "kind": "write",
  "params": [
   "session",
   "status"
  ]
 },
 "inbox": {
  "kind": "read",
  "params": [
   "session",
   "after",
   "to_me",
   "sender",
   "kind",
   "project",
   "limit",
   "unresolved"
  ]
 },
 "locks": {
  "kind": "read",
  "params": [
   "project",
   "all",
   "owner_session",
   "session"
  ]
 },
 "member_remove": {
  "kind": "write",
  "params": [
   "session",
   "name",
   "project",
   "client_id"
  ]
 },
 "member_set": {
  "kind": "write",
  "params": [
   "session",
   "name",
   "role",
   "project",
   "client_id"
  ]
 },
 "members": {
  "kind": "read",
  "params": [
   "session",
   "project"
  ]
 },
 "memory": {
  "kind": "read",
  "params": [
   "project",
   "kind",
   "query",
   "include_archived",
   "session"
  ]
 },
 "memory_add": {
  "kind": "write",
  "params": [
   "session",
   "kind",
   "title",
   "content",
   "source",
   "client_id"
  ]
 },
 "memory_edit": {
  "kind": "write",
  "params": [
   "session",
   "memory",
   "base_revision",
   "content",
   "status"
  ]
 },
 "poll": {
  "kind": "write",
  "params": [
   "session"
  ]
 },
 "post": {
  "kind": "write",
  "params": [
   "session",
   "body",
   "kind",
   "to",
   "reply_to",
   "claim",
   "client_id"
  ]
 },
 "post_commit": {
  "kind": "write",
  "params": [
   "session",
   "sha",
   "files"
  ]
 },
 "presence": {
  "kind": "read",
  "params": [
   "project",
   "include_dead",
   "session"
  ]
 },
 "profile_set": {
  "kind": "write",
  "params": [
   "session",
   "provider",
   "model_id",
   "model_family",
   "category",
   "reasoning_level",
   "capabilities"
  ]
 },
 "projects": {
  "kind": "read",
  "params": [
   "session"
  ]
 },
 "propose": {
  "kind": "write",
  "params": [
   "session",
   "discussion",
   "body",
   "supersedes",
   "client_id"
  ]
 },
 "react": {
  "kind": "write",
  "params": [
   "session",
   "proposal",
   "stance",
   "comment"
  ]
 },
 "release": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "all"
  ]
 },
 "renew": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "ttl"
  ]
 },
 "reply": {
  "kind": "write",
  "params": [
   "session",
   "message",
   "body",
   "kind",
   "client_id"
  ]
 },
 "resolve": {
  "kind": "write",
  "params": [
   "session",
   "message",
   "resolution",
   "client_id"
  ]
 },
 "revoke": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "to",
   "role"
  ]
 },
 "role_accept": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "role"
  ]
 },
 "role_decline": {
  "kind": "write",
  "params": [
   "session",
   "claim",
   "role",
   "reason"
  ]
 },
 "roles": {
  "kind": "read",
  "params": [
   "claim",
   "session"
  ]
 },
 "routine_create": {
  "kind": "write",
  "params": [
   "session",
   "title",
   "instructions",
   "every",
   "on_commit",
   "paths",
   "client_id"
  ]
 },
 "routine_done": {
  "kind": "write",
  "params": [
   "session",
   "routine",
   "result",
   "outcome"
  ]
 },
 "routine_get": {
  "kind": "read",
  "params": [
   "routine",
   "session"
  ]
 },
 "routine_start": {
  "kind": "write",
  "params": [
   "session",
   "routine"
  ]
 },
 "routine_update": {
  "kind": "write",
  "params": [
   "session",
   "routine",
   "status",
   "every",
   "instructions",
   "on_commit",
   "paths",
   "title"
  ]
 },
 "routines": {
  "kind": "read",
  "params": [
   "project",
   "due",
   "include_retired",
   "session"
  ]
 },
 "server_info": {
  "kind": "read",
  "params": []
 },
 "status": {
  "kind": "read",
  "params": [
   "project",
   "session"
  ]
 },
 "suggest": {
  "kind": "read",
  "params": [
   "project",
   "category",
   "capability",
   "reasoning_level",
   "exclude_session",
   "session"
  ]
 },
 "task_accept": {
  "kind": "write",
  "params": [
   "session",
   "task"
  ]
 },
 "task_cancel": {
  "kind": "write",
  "params": [
   "session",
   "task",
   "note"
  ]
 },
 "task_create": {
  "kind": "write",
  "params": [
   "session",
   "title",
   "description",
   "priority",
   "claim",
   "assign",
   "category",
   "after",
   "client_id"
  ]
 },
 "task_decline": {
  "kind": "write",
  "params": [
   "session",
   "task",
   "reason"
  ]
 },
 "task_done": {
  "kind": "write",
  "params": [
   "session",
   "task",
   "note"
  ]
 },
 "task_get": {
  "kind": "read",
  "params": [
   "task",
   "session"
  ]
 },
 "task_link": {
  "kind": "write",
  "params": [
   "session",
   "task",
   "after",
   "remove"
  ]
 },
 "tasks": {
  "kind": "read",
  "params": [
   "project",
   "status",
   "assigned_session",
   "session"
  ]
 },
 "thread": {
  "kind": "read",
  "params": [
   "message",
   "session"
  ]
 },
 "whoami": {
  "kind": "write",
  "params": [
   "family",
   "project",
   "user",
   "model",
   "client_id"
  ]
 }
};
