// schema/ops.json (the coord wire contract, generated from the Python service) -> src/ops.generated.ts
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const schema = JSON.parse(readFileSync(here("../../../schema/ops.json"), "utf8"));
const TS = { string: "string", integer: "number", boolean: "boolean", number: "number", "string[]": "string[]", object: "Record<string, unknown>" };

const lines = [
  "// GENERATED by scripts/gen-ops.mjs from schema/ops.json - do not edit.",
  "",
  `export const ENUMS = ${JSON.stringify(schema.enums)} as const;`,
  "",
  "export interface OpArgs {",
];
for (const [op, spec] of Object.entries(schema.ops)) {
  const fields = spec.params.map((p) => {
    const t = TS[p.type] + (p.nullable ? " | null" : "");
    return `${p.name}${p.required ? "" : "?"}: ${t}`;
  });
  lines.push(`  ${op}: { ${fields.join("; ")}${fields.length ? ";" : ""} };`);
}
lines.push("}", "", "export type OpName = keyof OpArgs;", "");
const table = Object.fromEntries(Object.entries(schema.ops).map(([op, s]) => [op, { kind: s.kind, params: s.params.map((p) => p.name) }]));
lines.push(`export const OPS: Record<OpName, { kind: "read" | "write"; params: readonly string[] }> = ${JSON.stringify(table, null, 1)};`, "");

writeFileSync(here("../src/ops.generated.ts"), lines.join("\n"));
console.log(`ops.generated.ts: ${Object.keys(schema.ops).length} ops`);
